---
title: "strike"
output: html_document
date: "2022-09-25"
---

ライブラリ
```{r}
library(tidyverse)
library(baseballr)
```


利用するデータ
```{r}
sho_id <- playerid_lookup(last_name = "Ohtani", first_name = "Sho") %>% 
  pull(mlbam_id)
data <- statcast_search_pitchers(start_date = '2022-09-20',
                                 end_date = '2022-09-26',
                                 pitcherid =  sho_id)

sho_p <- data %>% select(pitch_type, plate_x, plate_z, sz_top, sz_bot)

data <- statcast_search_batters(start_date = '2022-03-01',
                                 end_date = '2022-09-26',
                                 batterid =  sho_id)
sho_b <- data %>% select(events, plate_x, plate_z, sz_top, sz_bot)
```

## pitch_chart
```{r}
ggpitchchart <- function(data,
                         x_value = "plate_x",
                         z_value = "plate_z",
                         sz_top = NULL,
                         sz_bot = NULL,
                         lim = NA,
                         color_value = NULL,
                         density = FALSE,
                         bin_size = 8,
                         scall_fill_palette = "Blues",
                         point_size = 10,
                         point_alpha = 0.75,
                         div9 = TRUE,
                         base = FALSE,
                         title = NULL) {
  
  x1 <- x2 <- y1 <- y2 <- NULL
  
  strike_zones <- data.frame(
    x1 = rep(c(-0.83, -0.25, 0.25), each = 3),
    x2 = rep(c(-0.25, 0.25, 0.83), each = 3),
    y1 = rep(c(-0.83, -0.25, 0.25), 3),
    y2 = rep(c(-0.25, 0.25, 0.83), 3)
  )
  
  
  plot <- ggplot()+
    xlim(-lim, lim) + ylim(-lim, lim)+
    xlab("") + ylab("") +
    coord_fixed(ratio = 1) +
    theme(panel.background = element_blank(), axis.text = element_blank(), axis.ticks = element_blank(),
          plot.title = element_text(face = "bold", size = 25))
  
  if(!is.null(title)){
    plot <- plot +
      labs(title = title)
  }
  
  if(base){
    base <- data.frame(
  x = c(0, -1, -0.83, 0.83, 1),
  y = c(-2.4, -2.1, -1.66, -1.66, -2.1))
    
    plot <- plot +
      geom_polygon(base, mapping=aes(x=x, y=y), fill = "gray")
  }
  
  if(!density){
    plot <- plot+
      theme(legend.position = "right", legend.text = element_text(size = 17), legend.title = element_text(size = 17))
    
    if(div9){
      plot <- plot+
        geom_rect(data = strike_zones, aes(xmin = x1, xmax = x2, ymin = y1, ymax = y2), fill = "white", color = "gray20")
    }else{
      plot <- plot+
        geom_rect(aes(xmin = -0.83, xmax = 0.83, ymin = -0.83, ymax = 0.83), fill = NA, color = "gray20")
    }
    
    if(is.null(color_value)){
      if(!is.null(sz_top) && !is.null(sz_bot)){
        plot <- plot+
          geom_point(data = data, mapping = aes_string(x = x_value, y = paste("(1.66*(",z_value,"-",sz_bot,")/(",sz_top,"-",sz_bot,")-0.83)")),color = "blue", alpha = point_alpha, size = point_size)
      }else{
        plot <- plot+
          geom_point(data = data, mapping = aes_string(x = x_value, y = paste("(1.66*(",z_value,"-1.57)/(3.39-1.57)-0.83)")), color = "blue", alpha = point_alpha, size = point_size)
      }
    }else{
      
      if(!is.null(sz_top) && !is.null(sz_bot)){
        plot <- plot+
          geom_point(data = data, mapping = aes_string(x = x_value, y = paste("(1.66*(",z_value,"-",sz_bot,")/(",sz_top,"-",sz_bot,")-0.83)"), color = color_value), alpha = point_alpha, size = point_size)
      }else{
        plot <- plot+
          geom_point(data = data, mapping = aes_string(x = x_value, y = paste("(1.66*(",z_value,"-1.57)/(3.39-1.57)-0.83)"), color = color_value), alpha = point_alpha, size = point_size)
      }
    }
    
  }else{
    plot <- plot+
      theme(legend.position = "none")
    
    if(!is.null(sz_top) && !is.null(sz_bot)){
      plot <- plot+
        geom_density_2d_filled(data = data, aes_string(x = x_value, y = paste("(1.66*(",z_value,"-",sz_bot,")/(",sz_top,"-",sz_bot,")-0.83)")), bins = bin_size, alpha = 0.5)+
        scale_fill_brewer(palette = scall_fill_palette)
    }else{
      plot <- plot+
        geom_density_2d_filled(data = data,aes(x = x_value,y = paste("(1.66*(",z_value,"-1.57)/(3.39-1.57)-0.83)")),bins = bin_size, alpha = 0.5)+
        scale_fill_brewer(palette = scall_fill_palette)
    }
    
    if(div9){
      plot <- plot+
        geom_rect(data = strike_zones, aes(xmin = x1, xmax = x2, ymin = y1, ymax = y2), fill = NA, color = "gray20")
    }else{
      plot <- plot+
        geom_rect(aes(xmin = -0.83, xmax = 0.83, ymin = -0.83, ymax = 0.83), fill = NA, color = "gray20")
    }
    
  }
  
  return(plot)
}
```

```{r}
ggpitchchart(sho_data, x_value = "plate_x", z_value = "plate_z", sz_top = "sz_top", sz_bot = "sz_bot", color_value = "pitch_type", base = TRUE, title = "Ohtani, 9.24")
ggpitchchart(sho_data, x_value = "plate_x", z_value = "plate_z", sz_top = "sz_top", sz_bot = "sz_bot", lim = 2, density = TRUE, div9 = FALSE, title = "Ohtani, 9.24")
```
```{r}
df2 <- data.frame(
  x = c(0, -1, -0.83, 0.83, 1),
  y = c(-2.4, -2.1, -1.66, -1.66, -2.1)
)
ggpitchchart(sho_data)+
  geom_polygon(df2, mapping=aes(x=x, y=y), fill = "gray")
```


## zone_chart
```{r}
avg <- 0
for(i in 1:9){
  avg[i] <- sum(data$zone == i & data$events %in% c("single", "double", "triple", "home_run"))/sum(data$zone == 1 & data$events %in% c("single", "double", "triple", "k", "home_run", "field_out"))
}
```

```{r}
dTH <- 1:14

sapply(dTH, function(x){sum(zone == x, na.rm = TRUE)})
```


## hex_chart
```{r}
ggplot(data = sho_hits, aes(x = plate_x, y = (2.4*(plate_z-sz_bot)/(sz_top-sz_bot)-1.2))) +
  stat_bin_hex(binwidth = 0.4, geom = "text", aes(color = after_stat(count), size =  after_stat(count)), label = "⬢", family = "STIXTwoMath") +
  coord_fixed(ratio = 1) +
  scale_size(range = c(0,12))+
  theme(panel.background = element_blank(), axis.text = element_blank(), axis.ticks = element_blank())+
  geom_rect(aes(xmin = -0.83, xmax = 0.83, ymin = -1.2, ymax = 1.2), fill = NA, color = "gray") +
  xlab("") + ylab("")+
  xlab("") + ylab("")+
  labs(title = "Ohtani Hits -2022")
  
```

六角形を作る
```{r}
id <- seq(1, 1600)
y <- rep(seq(0, 38, by=2),20)

x <- (id-1) %/% 40
z <- data.frame(x, y)

z$y[x %% 2 == 0] <- z$y[x %% 2 == 0] + 1

z$y <- z$y*sqrt(3)
```
```{r}
ggplot(z)+
  geom_text(aes(x = x, y = y), label = "⬡", family = "AppleSymbols", size =4)+
  coord_fixed(ratio = 1)
```
距離を測る
```{r}
H <- cbind(z$x-20, z$y-20)
A <- cbind(sho_p$plate_x*5, sho_p$plate_z*5)
Z <- rbind(A,H)
Dist <- as.matrix(dist(Z))[nrow(A)+1:nrow(H), 1:nrow(A)]
Mins <- apply(Dist, 2, which.min)
```
```{r}
hsum <- NULL
for(i in 1:1600){
  hsum[i] <- sum(Mins==i)
}

glimpse(Dist)
glimpse(Mins)
```
plotする
```{r}
Data <- data_frame(z, hsum)
ggplot(Data)+
  geom_text(aes(x = x, y = y, size=hsum), label = "⬡", family = "AppleSymbols")+
  coord_fixed(ratio = 1)
```

打者だと..
```{r}
hits <- sho_b %>% 
  filter(events %in% c("HR", "single", "double", "triple"))%>% 
  drop_na(everything())

PA <- sho_b %>% 
  filter(!events %in% c("", "sac_fly", "sac", "walk")) %>% 
  drop_na(everything())

Hex_h <- cbind(z$x-20, z$y-20*sqrt(3))

hits_co <- cbind(hits$plate_x*5, (hits$plate_z-hits$sz_bot)/(hits$sz_top-hits$sz_bot)*13-6.5)
PA_co <- cbind(PA$plate_x*5, (PA$plate_z-PA$sz_bot)/(PA$sz_top-PA$sz_bot)*13-6.5)

Z <- rbind(hits_co, Hex_h)
Dist <- as.matrix(dist(Z))[nrow(hits_co)+1:nrow(Hex_h), 1:nrow(hits_co)]
Mins_h <- apply(Dist, 2, which.min)

Z <- rbind(PA_co, Hex_h)
Dist <- as.matrix(dist(Z))[1:nrow(PA_co), nrow(PA_co)+1:nrow(Hex_h)]
Mins_PA <- apply(Dist, 1, which.min)

Sum_PA <- NULL
for(i in 1:1600){
  Sum_PA[i] <- sum(Mins_PA==i)
}

Sum_h <- NULL
for(i in 1:1600){
  Sum_h[i] <- sum(Mins_h==i)
}

Avg <- Sum_h/Sum_PA
```

plotする
```{r}
Data <- data_frame(Sum_h, Avg, Hex_h)
base <- data.frame(
  x = c(0, -5, -4.15, 4.15, 5),
  y = c(-16.8, -15.3, -13, -13, -15.3))

ggplot()+
  theme(panel.background = element_blank(), axis.text = element_blank(), axis.ticks = element_blank())+
  geom_polygon(base, mapping=aes(x = x, y = y), fill = "gray")+
  geom_text(Data, mapping=aes(x = Hex_h[,1], y = Hex_h[,2], size = Sum_h, color = Avg), label = "⬢", family = "AppleSymbols")+
  scale_size(range = c(0, 10))+
  coord_fixed(ratio = 1)+
  geom_rect(aes(xmin = -4.15, xmax = 4.15, ymin = -6.5, ymax = 6.5), fill = NA, color = "gray20")+
  xlim(-10,10)+ylim(-20,15)
```


```{r}
ggplot(sho_b) +
  geom_point(mapping=aes(x=plate_x, y=plate_z, color=events))
```

